image: gitpod/workspace-dotnet

tasks:
  - init: |
      # Install .NET SDK
      mkdir -p $DOTNET_ROOT && \
      curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 7.0 --install-dir $DOTNET_ROOT
    command: |
      # Run tests after installation
      $DOTNET_ROOT/dotnet test
